steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.clojure', '-t', 'gcr.io/$PROJECT_ID/clojure', '.']
- name: 'gcr.io/$PROJECT_ID/clojure'
  args: ['-A:test']
images: ['gcr.io/$PROJECT_ID/clojure']

