FROM gcr.io/cloud-builders/java/mvn:3.5.0-jdk-8
RUN apt-get update \
 && apt-get install -y curl \
 && curl -O https://download.clojure.org/install/linux-install-1.10.1.478.sh \
 && chmod +x linux-install-1.10.1.478.sh \
 && ./linux-install-1.10.1.478.sh
ENTRYPOINT ["/usr/local/bin/clojure"]
